<script setup lang="ts">
import { FwbButton, FwbP, FwbHeading } from 'flowbite-vue'
</script>

<template>
  <div class="p-5 max-w-prose text-justify">
    <FwbHeading
      tag="h5"
      class="text-2xl font-bold tracking-tight text-gray-900"
    >
      Participating in a research project
    </FwbHeading>
    <FwbP class="font-normal text-gray-700">
      Dear participant,
    </FwbP>
    <FwbP class="font-normal text-gray-700">
      You are being invited to participate in a research study titled
      <strong class="font-semibold text-gray-900">Contemporary Creativity: The Many Faces of AI Art.</strong> This
      study is being carried out by Jari de Keijzer, a Bachelor student in Computer Science and Engineering at Delft
      University of Technology, under supervision of Dr. Anna Lukina.
    </FwbP>
    <FwbP class="font-normal text-gray-700">
      The purpose of this research is to discover whether images that are generated by a specific Artificial
      Intelligence (AI) model can appear to be creative. To answer this question, you, the participant, will vote on
      the creativity of pairs of pictures. For each pair of images, you will vote on which one you find the most{' '}
      <strong class="font-semibold text-gray-900">novel, surprising or valuable.</strong> This means that for each
      pair of images you will enter three votes. The pairs of images will contain AI generated images, and
      non-generated images out of the real world. The AI images will have both inlier (more realistic) en outlier
      (stranger) images. During the voting process you will NOT be shown what category the image belongs too, this is
      part of the experiment. Participating in this research will take you about 15 minutes to complete.
    </FwbP>
    <FwbP class="font-normal text-gray-700">
      This research is completely anonymous, so NO personal data will be collected. This voting website is hosted on a
      TU Delft owned server, on which no other data than your anonymous votes will be collected. These votes will be
      used to rank the images according to an ELO score (known from chess). With this ranking the creativity of the AI
      model will be evaluated. The collected votes, the ELO ranking, and the evaluated results will be published and
      presented in a paper which will be publicly available on the TU Delft research repository.
    </FwbP>
    <FwbP class="font-normal text-gray-700">
      Anyone of the age of <strong class="font-semibold text-gray-900">18 years or older</strong> is allowed to
      participate in this research. It is important for this research to get a diverse collection of votes. More
      participants will increase the accuracy of the ranking. On that note, you, the participant, are allowed to share
      this research with others.
    </FwbP>
    <FwbP class="font-normal text-gray-700">
      Your participation in this study is entirely voluntary and you can withdraw at any time. Since the votes are
      completely anonymous, they cannot be linked to you, which makes deleting ‘your’ votes impossible after
      submission.
    </FwbP>
    <FwbP class="font-normal text-gray-700">
      Continuing to the next screen will start the voting process, which means you will be an anonymous participant.
    </FwbP>
    <FwbP class="font-normal text-gray-700">
      Any questions or remarks can be sent to the following email address:
      <a
        href="mailto:j.n.dekeijzer@student.tudelft.nl?subject=Research Project"
        class="font-medium text-TUcyan underline hover:text-TUdarkblue hover:no-underline"
      >
        j.n.dekeijzer@student.tudelft.nl
      </a>
    </FwbP>
    <FwbP class="font-normal text-gray-700">
      Thank you for your time and participation,
    </FwbP>
    <FwbP class="font-normal text-gray-700">
      Jari de Keijzer
    </FwbP>
    <FwbButton
      href="/explanation"
      class="bg-TUcyan hover:bg-TUdarkblue focus:outline-none focus:ring-4 focus:ring-TUblue active:outline-none active:ring-4 active:ring-TUblue"
    >
      I understand the above and want to participate
      <svg
        class="size-[24px] inline"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        fill="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M19 12H5m14 0-4 4m4-4-4-4"
        />
      </svg>
    </FwbButton>
  </div>
</template>

<style scoped>

</style>
