<script setup lang="ts">
import { FwbP, FwbHeading, FwbCard } from 'flowbite-vue'
</script>

<template>
  <FwbCard
    variant="horizontal"
    class="p-5 max-w-prose text-justify"
  >
    <FwbHeading
      tag="h5"
      class="mb-2 text-2xl font-bold tracking-tight text-gray-900"
    >
      Participating in research
    </FwbHeading>
    <FwbP>
      Dear participant,
    </FwbP>
    <FwbP>
      You are being invited to participate in a research study titled
      <strong class="font-bold text-gray-900">Contemporary Creativity: The Many Faces of AI Art.</strong> This
      study is being carried out by Jari de Keijzer, a Bachelor student in Computer Science and Engineering at Delft
      University of Technology, under supervision of Dr. Anna Lukina.
    </FwbP>
    <FwbP>
      The purpose of this research is to discover whether images that are generated by a specific Artificial
      Intelligence (AI) model can appear to be creative. To answer this question, you, as participant, will vote on
      the creativity of pairs of pictures. For each pair of images, you will vote on the image that you find the most
      <strong class="font-bold text-gray-900">novel, surprising or valuable.</strong> This means that for each
      pair of images you will enter three votes. The pairs of images will contain both AI generated as non-generated
      images. The AI images will have both more realistic (inlier) and stranger (outlier) images. During the voting
      process you will NOT be shown what category the image belongs too, this is part of the research. Participating
      in this research will take you about 15 minutes to complete.
    </FwbP>
    <FwbP>
      This research is <strong class="font-bold text-gray-900">completely anonymous</strong>, so NO personal data will
      be collected. This voting website is hosted on a TU Delft owned server, on which no other data than your anonymous
      votes will be collected. These votes will be used to rank the images according to an ELO score (explained on the
      next page). With this ranking the creativity of the AI model will be evaluated. The collected votes, the ELO
      ranking, and the evaluated results will be published and presented in a paper which will be publicly available
      on the TU Delft research repository.
    </FwbP>
    <FwbP>
      Anyone of the age of <strong class="font-bold text-gray-900">18 years or older</strong> is allowed to
      participate in this research. It is important for this research to get a diverse collection of votes. More
      participants will increase the accuracy of the ranking. On that note, you, the participant, are allowed to share
      this research with others.
    </FwbP>
    <FwbP>
      Your participation in this study is entirely voluntary and you can withdraw at any time. Since the votes are
      completely anonymous, they cannot be linked to you, which makes deleting ‘your’ votes impossible after
      submission.
    </FwbP>
    <FwbP>
      Continuing to the next screen will start the voting process, which means you will be an anonymous participant.
    </FwbP>
    <FwbP>
      Any questions or remarks can be sent to the following email address:
      <NuxtLink
        to="mailto:j.n.dekeijzer@student.tudelft.nl?subject=Research Project"
        class="font-medium text-TUcyan underline hover:text-TUdarkblue hover:no-underline"
      >
        j.n.dekeijzer@student.tudelft.nl
      </NuxtLink>
    </FwbP>
    <FwbP>
      Thank you for your time and participation,
    </FwbP>
    <FwbP>
      Jari de Keijzer
    </FwbP>
    <NuxtLink
      to="/explanation"
      class="flex py-2.5 px-5 rounded-lg font-medium text-TUwhite w-full bg-TUcyan text-base hover:bg-TUdarkblue focus:ring-2 focus:outline-none focus:ring-TUblue active:ring-4 active:ring-TUblue"
    >
      I understand and want to participate
      <svg
        class="size-[24px] inline"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        fill="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M19 12H5m14 0-4 4m4-4-4-4"
        />
      </svg>
    </NuxtLink>
  </FwbCard>
</template>

<style scoped>

</style>
